baseURL = 'https://trotsky.su/'
languageCode = 'ru'
defaultContentLanguage = "ru"
title = 'Место'
theme = 'tale'
disableFastRender=true
[Author]
  name = "Маяк Александрийский"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
