baseURL = 'https://trotsky.su/'
languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Место'
theme = 'tale'
[Params]
  [Params.Author]
    name = 'Маяк Александрийский'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Картотека"
    title = "Картотека"
    url = "/archives.html"
    weight = 1
