baseURL = 'https://trotsky.su/'
languageCode = 'en-us'
title = 'Место'
theme = 'tale'
[Params]
  [Params.Author]
    name = 'Маяк Александрийский'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
